### ISSUE TITLE
[TwigComponent] twig:lint doesn't mark non-existing components as errors

### ISSUE THREAD

**Issue by ebitkov** [symfony/ux#1281]
Not sure if this is an error or expected behavior, but `lint:twig` doesn't mark non-existing components as errors.

I recently removed some components from my 400+ files project and was fooled by the "OK" message. Luckily I had a staging environment, where the error popped up, before it went to prod.

### How to reproduce

1. Create a blank Symfony project and install `symfony/ux-twig-component`
2. Create a new controller
3. Add to your template file `<twig:hello-world/><twig:hello-world></twig:hello-world>`
4. Visit the route of your controller from step 2 >> **you get an "Unknown component 'hello-world'" exception**
5. Run `console lint:twig` >> **you get "[OK]"**

#1089 fixed a bug in `lint:twig`, where anonymous components where marked as non-existing. Maybe there is a correlation.

**Comment by smnandre** [comment]
The twig linter only does a static analysis... so your syntax is correct :) 

The resolution of "hello-world" is done on render time so the linter is blind for that kind of problem.

You are 100% right, this is something that had to change due to bugs with anonymous components (but not only that, with events too) and features we could not have kept otherwise

It's the same behaviour for almost every twig function/tag/etc.

You can try this line of code (in any template)...  For lint:twig it's valid

```twig
{{ include('this_template_does_not_exist.html.twig') }}
```

**Comment by ebitkov** [comment]
Well, that makes sense, I guess. 
Since this is neither a bug, nor a plant feature, I'm going to close this as a documentation for people wondering the same as me.
