### ISSUE TITLE
[TwigComponent] Cva in html_extra

### ISSUE THREAD

**Issue by smnandre** [symfony/ux#2070]
It seems the cva function will be merged into twig/html-extra (see https://github.com/twigphp/Twig/pull/4006) 

How do we handle the transition ? 

* Add a conflict with the future version of html-extra here seems not a good idea, as this would be blocking for future updates
* Add a deprecation layer here ?
* Ask people to require twig/html-extra ? 
* What do we do about the documentation ?

**Comment by Kocal** [comment]
We should be careful here since the `cva()` definition changes from here and from https://github.com/twigphp/Twig/pull/4006:
1. actual: `public function cva(array $cva): CVA`
2. https://github.com/twigphp/Twig/pull/4006: `public static function cva(array|string|null $base = null, ?array $variants = null, ?array $compoundVariants = null, ?array $defaultVariant = null): Cva`

This first one takes a big array, where the second one takes advantage of Twig named arguments (and that's super nice! I prefer this syntax too), but, we should find a way to correctly handle the migration from UX to twig/html-extra for `cva`. 

If https://github.com/twigphp/Twig/pull/4006 is merged, it has no interest to keep CVA's code in UX and we will need to remove it, in a **major** version.

If release a new major version is not wanted - which I agree because it will affect all other UX packages -, I think we can do it smoothly by:
1. makes `symfony/ux-twig-component` requires `twig/extra-html`
2. implement a "bridge" in `symfony/ux-twig-component` to nicely migrate and warn the user about passing an array to `cva`
3. trigger a deprecation, telling the user to manually requires `twig/extra-html` and pass named arguments
4. tag a new minor version

Then, for a new major version, remove this deprecation layer and `twig/extra-html` dependency.

For the documentation, I believe we can do something like:
> Since 2.2x, `cva` function has moved to `twig/extra-html`. 
> We recommend you to upgrade your `cva` usages to (...),  since `cva` will be removed from UX Twig Components (...).

WDYT?

**Comment by smnandre** [comment]
> 1. makes symfony/ux-twig-component requires twig/extra-html

I'm not in favor of requiring an external package (this would need twig-extra too) ... to deprecate one

And that does not change the fact someone updating twig/extra-html will break its app, no ? Two functions cannot be registered with the same name i think.

**Comment by smnandre** [comment]
@WebMamba renamed the `twig/html-extra` function  `html_cva` to ease this transition / diminish any conflict risks (thank you for this)

So indeed, next steps here:
* once `html_cva` is released on `twig/html-extra`: deprecate the `cva` function (and suggest the twig version)
* next major release of TwigComponent: remove the `cva` function

**Comment by Kocal** [comment]
@smnandre I'm not sure why you closed this issue, our `cva` function is still not deprecated right?

**Comment by smnandre** [comment]
This issue was to decide the "what to do" .. and we did .. but let's reopen if you prefer to keep a "todo" !

**Comment by Kocal** [comment]
Ah, yes ok, it makes sense!
I would prefer if we re-open this issue or directly create another one, so our plan is not lost 🙏🏻
