### ISSUE TITLE
[Translator] Add an option to throw an exception instead of returning the message as is when the translation is not found.

### ISSUE THREAD

**Issue by Crovitche-1623** [symfony/ux#2183]
For some translations, the `id` (the key in other words) is the same as the translations (e.g. the `Invalid credentials.` in the security domain):

```js
export const INVALID_CREDENTIALS = {"id":"Invalid credentials.","translations":{"security":{"fr":"Identifiants invalides.","en":"Invalid credentials.","de":"Fehlerhafte Zugangsdaten.","it":"Credenziali non valide."}}};
```

Therefore, there is no way in the frontend to distinguish a missing translation from a translation that have the same `id` (key) same as a translation because the only way I found in the frontend to detect if the translation is missing is checking if the result from the `trans` method is the same as the id. For example:

```js
const translationConstant = aServiceThat.findConstantById(messageId);

// I'm voluntarily trying in the default domain (`messages`) even though I know the message isn't there.
let translatedMessage = translator.trans(translator[translationConstant]);

if (translatedMessage === translator[translationConstant].id) {
    // Here how I distinguish a missing translation from a translation that have a same value as his id when no exception is thrown. If an exception was thrown, I could try something else (e.g. search in another domain)
}
```

To solve this problem, I think we could pass an additional to the `trans` method with a default value (`throwWhenNotFound = false`) and catch the exception later.

**Comment by Kocal** [comment]
Hi, thanks for rising this use-case, it actually makes sense and I think I would like to see it in Translator. :)

However, I do not like the fact for `trans` to accept a new parameter for two reasons:
1. We do not use named parameter, so developers will be forced to pass parameters they probably want to. The translation parameters, the catalogue name, and the locale, in order to pass `true` to throw if the translation does not exist
2. I don't want `trans()` from Symfony UX to diverge from the Symfony Translator (PHP), such an option `throwWhenNotFound` is a no go

A good alternative would be to make this option globally configurable, like `_locale` with `setLocale()`, like `_localeFallbacks` with `setLocaleFallbacks()`. 
In the UX Translator Configuration, add a new boolean config like `throw_when_not_found` (the name can be improved tho), which will be applied to all `trans()` calls without touching its signature.

WDYT?

**Comment by Crovitche-1623** [comment]
Yes, that's great. Thanks for the feedback @Kocal. I can try to implement it but it will take some time as I'm not good at JS/TS.

**Comment by Kocal** [comment]
> I can try to implement it but it will take some time as I'm not good at JS/TS.

Don't worry, it should be more simple than what you already did!

However, feel free to ask for help if needed :)
