### ISSUE TITLE
Vue Component

### ISSUE THREAD

**Issue by TavoNiievez** [symfony/ux#22]
Would it be possible to create a component for Symfony UX that does what [Inertia JS](https://inertiajs.com/) currently does?

ie, hydrate the props of a Vue component from the server-side with Symfony/PHP, and render that same component in a Twig template with some twig helper function ?

**Comment by tgalopin** [comment]
Hi!

"Live" templating is a domain we are looking into. However, it's important IMO that 1/ we don't hide any JavaScript (like Livewire tends to do) as our aim should not be to replace JavaScript by PHP just for the sake of it and 2/ we should always use standard protocols that can be used by another JS implementation, so that one could use it without Stimulus if useful.

There are interesting ideas to have a look at, it's something we are working on. If you or someone else has ideas, feel free to ping me!

**Comment by Kocal** [comment]
Can be closed since #426
