### ISSUE TITLE
[UX Turbo] - Property 'Turbo' does not exist on type 'Window & typeof globalThis'.

### ISSUE THREAD

**Issue by jodeca** [symfony/ux#284]
Hi, when typescript with turbo, i have error:

[tsl] ERROR in vendor\symfony\ux-turbo\Resources\assets\src\turbo_controller.ts(14,8)
      TS2339: Property 'Turbo' does not exist on type 'Window & typeof globalThis'.

Please, help me.

Note: Sorry for my english.

Thanks

**Comment by weaverryan** [comment]
Is this an actual error or just a TypeScript warning? I'm not sure we support importing our typescript files directly: I believe you should import our normal, JavaScript files, even if we're using TypeScript internally. But someone that uses TS more regularly could correct me if I'm wrong.

**Comment by jodeca** [comment]
Thanks

**Comment by amouhzi** [comment]
I have the same issue. With strict typescript mode, we cannot import directly javascript files because this library has no definition (index.d.ts files), so we try to import directly typescript files.

More info:
- https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
- https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html
