### ISSUE TITLE
[Autocompleter] Support a way to customise the search query

### ISSUE THREAD

**Issue by bendavies** [symfony/ux#333]
Hi,

(continuing from slack)

Autocompleter looks amazing, thankyou! 
Just what we needed right now.

The ask: 
We'd like way to customise the search query performed by auto completer.
Esentially, I don't want any of the logic done by `EntitySearchUtil::addSearchClause()`, and I want to supply my own query.

Background: we need to use [PostgreSQL's FTS](https://www.postgresql.org/docs/14/textsearch.html) to query results, because:
1. we have large numbers of entities, so I don't want to use `LIKE` queries.
1. ability to get better more relevent results.

I don't need Autocompleter to support FTS fields, just a ability to plug in my own query.

Let me know if that's clear enough.
Thanks!

**Comment by weaverryan** [comment]
We might add a new method to https://github.com/symfony/ux/blob/2.x/src/Autocomplete/src/EntityAutocompleterInterface.php:

```php
public function applySearch(QueryBuilder $queryBuilder, string $query, EntitySearchUtil $searchUtil, array $searchableProperties = null): QueryBuilder;
```

Normally this isn’t an interface users need to implement directly anyways. But if they did, and wanted to use the normal way of searching, they would:

```php
public function applySearch(QueryBuilder $queryBuilder, string $query, EntitySearchUtil $searchUtil, array $searchableProperties = null): QueryBuilder
{
    return $searchUtil->addSearchClause($queryBuilder, $query, $this->getEntityClass(), $searchableProperties);
}
```

In the "normal world", we would add a new option to https://github.com/symfony/ux/blob/2.x/src/Autocomplete/src/Form/ParentEntityAutocompleteType.php called `filter_query`. If specified, than THAT would be used instead of calling the `EntitySearchUtil`. So, the https://github.com/symfony/ux/blob/2.x/src/Autocomplete/src/Form/WrappedEntityTypeAutocompleter.php would have logic to look for this and use it (or not use it) inside its `applySearch()` method.
