### ISSUE TITLE
Attributes and `data-loading`

### ISSUE THREAD

**Issue by norkunas** [symfony/ux#372]
In [loading states docs](https://symfony.com/bundles/ux-live-component/current/index.html#loading-states) there is a statement:
```
Often, you'll want to show (or hide) an element while a component is re-rendering or an action is processing.
```

But for me it doesn't work as expected.
I have a pagination component which is used in a live component. There are two buttons: prev and next.
If I am on page 1, then the I add the `disabled` attribute on it in the twig, and same with last page.
When I initially load the page, that attribute get's removed.

So the docs should indicate that it will run also on initial load?

My use case is that I want to disable buttons when I've clicked on them, to indicate that request is already processing.
But there is also a problem, that the attribute will be always removed because of:
```
case 'addAttribute':
            return isLoading ? 'addAttribute' : 'removeAttribute';
```

I can think only a workaround to add `data-loading` only if the button must not be disabled..
Or do you think that this use case would be more common so we could add some way to do this easier?

**Comment by weaverryan** [comment]
just as a first suggestion, could you *avoid* adding the `data-loading` in Twig when the button is disabled? If I understand things correctly, if (for example) `page=1`, then you will add a `disabled` attribute to the "page 1" link. In that case, the `data-loading` doesn't make any sense on that link, right? It is disabled and should *always* be disabled - no loading behavior is needed on that button. Then, once the user clicks to page 2, the template would re-render and you could then add the `data-loading`.

WDYT? I'm not saying we shouldn't do some sort of code fix, but I'm not sure yet :). The reason we run the "loading has stopped" logic on initial load is so that if you have a `data-loading="show"` on an element, we can hide that element immediately after initial load. We certainly *could* make this smarter so that ONLY this rule runs on "initial load", and all other `data-loading` mechanisms do NOT run on initial load. PR welcome for that if it makes sense ;)
