### ISSUE TITLE
[Autocomplete] Support for Virtual Scrolling/Pagination

### ISSUE THREAD

**Issue by bendavies** [symfony/ux#399]
Hi,

Support for [Virtual Scroll](https://tom-select.js.org/plugins/virtual_scroll/) is included in the javascript:
https://github.com/symfony/ux/blob/8e84d49a92b70f99001b8817cd3129a6215175f6/src/Autocomplete/assets/src/controller.ts#L131

But there is no support in the default php implmentation.
Basically, the backend needs to support pagintion fo the data, returning a `next_page` item in the response, if there are more results.

**Comment by bruno-buiret** [comment]
I am also interested in this :)

**Comment by weaverryan** [comment]
I haven't looked into this yet, but it should be reasonably easy:

A) in the controller, we would likely need to pass the `page` query parameter into the `AutocompleteResultsExecutor` as a new argument: https://github.com/symfony/ux/blob/5f484d6908a1a2dd5cf5cb00712b6009c771257b/src/Autocomplete/src/Controller/EntityAutocompleteController.php#L41

B) In `AutocompleteResultsExecutor`, we would need to introduce Doctrine's paginator (we already get a `QueryBuilder`, so that shouldn't be too hard). 

C) The `AutocompleteResultsExecutor` would now probably need to return MORE than just the `$results`: it would likely need to include the next page integer or null if there is no next page. Perhaps this method should now return a value object containing that info.

D) Back in the controller, the "next page" returned by `AutocompleteResultsExecutor` would be used to generate the URL to the next page and included on a `next_page` key in the JSON. To generate the URL, we should probably get the current URL, then replace any `?page` query parameter with the new "next page" (we could do this by cloning the current `Request` object, calling `$request->query->set('page', $nextPage)`, then calling `$request->getRequestUri()` I believe).

If someone wants to open a PR, that'd be awesome :)
