### ISSUE TITLE
[Autocomplete] Add a way to require a minimum char number to before send ajax request 

### ISSUE THREAD

**Issue by nfacciolo** [symfony/ux#432]

**Comment by daFish** [comment]
Hey @weaverryan, what would be the best place to implement such an option?

**Comment by weaverryan** [comment]
Good question - because I'd love to see a PR for this.

It looks like TomSelect has a `shouldLoad()` option for this - https://tom-select.js.org/docs/

We use `shouldLoad`... sort of right now - just to hide the "No results" message when you are NOT using Ajax. We could allow a new option to be passed into the Stimulus controller - e.g. `minCharacters` - that, when set, we would use to have a proper `shouldLoad` function.

To do this, you'd need a few pieces - you can use `noResultsFoundText` as a guide:

A) Add the option to the form type - https://github.com/symfony/ux/blob/7a2eda6af227a65cc1912e25b5ab98c368dc78ce/src/Autocomplete/src/Form/AutocompleteChoiceTypeExtension.php#L93
B) Transform that option into the `data-` attribute used for Stimulus values - e.g. https://github.com/symfony/ux/blob/7a2eda6af227a65cc1912e25b5ab98c368dc78ce/src/Autocomplete/src/Form/AutocompleteChoiceTypeExtension.php#L70-L72
C) In the Stimulus controller, add the new value - https://github.com/symfony/ux/blob/7a2eda6af227a65cc1912e25b5ab98c368dc78ce/src/Autocomplete/assets/src/controller.ts#L9 (and the fake property below to make TypeScript happy).
D) Use that value down below inside the Stimulus controller

Cheers!
