### ISSUE TITLE
[Website] Submitting turbo stream results in 500

### ISSUE THREAD

**Issue by BeyerJC** [symfony/ux#442]
Hi, when i submit the Turbo Stream example, i  get the 500 error page. After i navigate back to the same example, the selected chat message is displayed.

Maybe we can check logs to investigate. Im open for PR if needed.

**Comment by weaverryan** [comment]
I did a deploy today... and I must've broken something!

The error is:

> {"message":"Matched route \"app_turbo_chat\".","context":{"route":"app_turbo_chat","route_parameters":{"_route":"app_turbo_chat","_controller":"App\\Controller\\TurboController::turboChat"},"request_uri":"https://ux.symfony.com/turbo/chat","method":"POST"},"level":200,"level_name":"INFO","channel":"request","datetime":"2022-08-25T00:38:39.168688+00:00","extra":{}}
{"message":"Uncaught PHP Exception Lcobucci\\JWT\\Signer\\InvalidKeyProvided: \"Key provided is shorter than 256 bits, only 224 bits provided\" at /app/vendor/lcobucci/jwt/src/Signer/InvalidKeyProvided.php line 39","context":{"exception":{"class":"Lcobucci\\JWT\\Signer\\InvalidKeyProvided","message":"Key provided is shorter than 256 bits, only 224 bits provided","code":0,"file":"/app/vendor/lcobucci/jwt/src/Signer/InvalidKeyProvided.php:39"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2022-08-25T00:38:39.185145+00:00","extra":{}}

Odd, because nothing has changed lately that I can think of related to JWT stuff.  If someone knows the cause and can open a PR, that'd be 💯 . Otherwise, I'll check into it tomorrow :)
