### ISSUE TITLE
[UX-Turbo] When create a chat it is not possible to identify the current user receiving the stream update

### ISSUE THREAD

**Issue by nfacciolo** [symfony/ux#445]
In the controller implementing this:
```
$hub->publish(new Update(
                $chatRoom->getRoomName(),
                $this->renderView('chat/broadcast/message.stream.html.twig', [
                        'chatRoom' => $chatRoom,
                        'receiver' => $receiver,
                        'message' => $message,
                    ]
                ),

            ));
```
In the view implementing this:

```
{# Learn how to use Turbo Streams: https://github.com/symfony/ux-turbo#broadcast-doctrine-entities-update #}
{# New messages received through the Mercure connection are appended to the div with the "messages" ID. #}
<turbo-stream action="append" target="messages">
    <template>
        {{ app.user.id }};
        {% if message.sender == app.user %}
            {{ include('chat/row/sender.html.twig') }}
        {% else %}
            {{ include('chat/row/receiver.html.twig') }}
        {% endif %}
    </template>
</turbo-stream>
```

It's not possible to identify the publication receiver: `app.user.id` is all time the sender message id so it's impossible to customize the live updated view according to the sender or receiver (add sender avatar, put text to the right or left...)

Is it possible to get this information in live ?

**Comment by weaverryan** [comment]
Hi!

I'm not sure exactly what you want to do, but I think I can help clarify what's possible :). When you publish the `Update` in the controller, you are publishing ONE update that will be sent to ALL users that are listening to that topic. Because you are just publishing ONE update for everyone, you can't customize what the HTML in that update looks like: it will be the same for everyone. So, you cannot, for example, make "User A)" receive HTML that has the avatar and "User B)" receive that same update with different HTML that does not have the avatar. That's simply not possible.

What you *could* do is leverage a turbo frame. I've never done this, but it should work - something like this:

```twig
<turbo-stream action="append" target="messages">
    <template>
        <turbo-frame src="{{ path('app_render_chat_message', { id: message.id }) }}"></turbo>
</turbo-stream>
```

I will talk about the `app_render_chat_message` route in a moment. But for now, pretend it renders `/chat/messages/1`. The idea is this:

A) This HTML is sent to ALL users. So, all users would suddenly have a `<turbo-frame src="/chat/messages/1">` on their page in the correct location.

B) As soon as that is rendered, the `turbo-frame` will make an Ajax request to that URL.

C) You will build a controller + route that will return just the ONE message. But since this endpoint is being rendered via Ajax by each individual user's browser, you WILL have access to the current user and can make changes. For example:

```php
#[Route('/chat/messages/{id}', name: 'app_render_chat_message')]
public function renderChatMessage($id): Response
{
    $message = ''; // look up the Message object in the database from the $id

    return $this->render('chat/_message.html.twig', ['message' => $message]);
}
```

The template would look very much like your update template did before:

```twig
        {% if message.sender == app.user %}
            {{ include('chat/row/sender.html.twig') }}
        {% else %}
            {{ include('chat/row/receiver.html.twig') }}
        {% endif %}
```

I hope this helps :)

**Comment by nfacciolo** [comment]
HI dude, 

Thanks a lot for you response: this solution works but make one more requests per chat message. 
I found out another working convenient solution:


```
<turbo-stream action="append" targets=".sender_{{ message.sender.id }}">
    <template>
        {{ include('chat/row/sender.html.twig') }}
    </template>
</turbo-stream>
<turbo-stream action="append" targets=".receiver_{{ receiver.id }}">
    <template>
        {{ include('chat/row/receiver.html.twig') }}
    </template>
</turbo-stream>

```

```
{% block content %}

    <img src={{ path('app_album_image_show', {'id': receiver.getAvatar.id}) }}>
    <h1>{{ receiver.customer.firstName }}</h1>

    <div class="sender_{{ app.user.id}} receiver_{{ app.user.id }}" {{ turbo_stream_listen(chatRoom.roomName) }}>
        {% for message in chatRoom.messages %}
            {% if message.sender == app.user %}
                {{ include('chat/row/sender.html.twig') }}
            {% else %}
                {{ include('chat/row/receiver.html.twig') }}
            {% endif %}
        {% endfor %}
    </div>

    <turbo-frame id="message_form">
        {{ form(form) }}
    </turbo-frame>
{% endblock %}

```
