### ISSUE TITLE
[Autocomplete] overriding the default query_builder option is not used on ajax autocomplete

### ISSUE THREAD

**Issue by jvancoillie** [symfony/ux#474]
### Description
Overriding the default `query_builder` option is not used on ajax autocomplete, it looks like only the default option is considered.

Also, it is not possible to omit the default configuration (FoodAutocompleteField) of the query_builder otherwise we end up with the same problem as expressed in #420

### How to reproduce
override the default query_builder option in the form (AnyForm.php)

```php
// src/Form/FoodAutocompleteField.php
// ...

use Symfony\Component\Security\Core\Security;
use Symfony\UX\Autocomplete\Form\AsEntityAutocompleteField;
use Symfony\UX\Autocomplete\Form\ParentEntityAutocompleteType;

#[AsEntityAutocompleteField]
class FoodAutocompleteField extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'class' => Food::class,
            'placeholder' => 'What should we eat?',
            'query_builder' => function(FoodRepository $foodRepository) {
                return $foodRepository->createQueryBuilder('food')
                    ->innerJoin('food.type', 'type')
                    ->orderBy('type')
                ;
            }
        ]);
    }

    public function getParent(): string
    {
        return ParentEntityAutocompleteType::class;
    }
}
```

```php
// src/Form/AnyForm.php
// ...

class AnyForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
         $builder
            ->add('food', FoodAutocompleteField::class, [
                'query_builder' => function(FoodRepository $foodRepository) {
                    return $foodRepository->createQueryBuilder('food')
                        ->innerJoin('food.type', 'type')
                        ->where('type = :type')
                        ->setParameter('type', 'meat')
                    ;
                }
            ]);
    }
}
```

**Comment by weaverryan** [comment]
Hi!

This is true: you really cannot pass/override ANY options when you use an Ajax auto-complete field. This is because, on the Ajax call, we would have no way to re-create your `AnyForm` form (nor are we even aware of it). We simply re-create the `FoodAutocompleteField` and then use its `query_builder`.

There *is* a problem/shortcoming here for sure though. You can see it by looking at this example, #420 and also #391. To summarize: there needs to be a way to "configure"/parameterize an autocomplete field so that it can work slightly differently in different contexts. This looks like a combination of having some extra "context" that you can force to be included in the Ajax call (https://github.com/symfony/ux/issues/391#issuecomment-1183351864) and also some way to pass this *into* your custom autocomplete field (e.g. `AutocompleteFieldType`) - like as a `query_context` option.

I've just clarified the docs in #475. I'm going to close this issue - only because it's a duplicate imo of #391.

Cheers!

**Comment by weaverryan** [comment]
Btw, the workaround until we have #375 working is to create your own autocompleter as described in the docs or here https://github.com/symfony/ux/issues/391#issuecomment-1209956306
