### ISSUE TITLE
[LiveComponent] Input field's default value not in request

### ISSUE THREAD

**Issue by barbieswimcrew** [symfony/ux#694]
Hi all, I have stumbled across a strange behavior: _**For example**_, when I create a TextType field without a default "data" value, the field initially correctly displays "empty". When I submit the form, the request also correctly shows the field without data.

If I now subsequently change the value of the field via JS and then submit the form, the value in the request remains empty.

However, if I manually change the value of the field by keyboard input, the value is correctly submitted in the request.

This behavior currently presents me with a challenge when implementing a captcha field using the [FriendlyCaptchaBundle](https://github.com/cors-gmbh/friendly-captcha-bundle) and associated with this the use of the [Friendly Challenge Javascript Widget](https://github.com/FriendlyCaptcha/friendly-challenge).

I include the widget as follows and reset it on "render:finished" to get the widget rendered properly even after re-rendering the form.

```
'use strict';

import {getComponent} from '@symfony/ux-live-component';
import {Controller} from "@hotwired/stimulus";
import {WidgetInstance} from "friendly-challenge";

/* stimulusFetch: 'lazy' */
export default class ContactFormController extends Controller {
    async initialize() {
        this.component = await getComponent(this.element).then((component) => {
            const widget = new WidgetInstance(document.querySelector('.frc-captcha'));
            
            component.on('render:finished', (component) => {
                widget.reset();
            });
        });
    }
}
```

The widget renders a hidden field whose value is a generated string needed for an API request during validation. Unfortunately, the value of the field in the request is always empty.

Only when I change the field from "hidden" to "text" with the Developer Toolbar and additionally change the value of the field manually via keyboard input, only then the value is transmitted correctly via request.

To be honest, I am at a loss as to what the cause is here, so I really hope someone can help me. 

Thanks in advance for the efforts!

**Comment by weaverryan** [comment]
Hi there!

I think I know the problem. And if so, it’s super annoying. Check the last paragraph in this section about triggering an event: https://symfony.com/bundles/ux-live-component/current/index.html#working-with-the-component-in-javascript

The problem is that when the captcha bundle sets the value onto the hidden input, no JavaScript event is dispatched. Basically, when you type in a field, a “change” event is dispatched in js. But if something sets the value of a field directly, there is actually NO event or way for live components to be aware of that :/. And so, while the hidden input has been updated, the live component is unaware of the change. The docs show how to solve this problem, but it’s an unfortunate thing to need to “work around” in the first place.

Let me know if that was the issue. 

Cheers!

**Comment by barbieswimcrew** [comment]
@weaverryan maaaaaan, you definitely made my day!!! That's exactly where the dog was buried! Thank you so much and sorry for bothering you!

**Comment by weaverryan** [comment]
No worries - this is a "thorn in my side" - and it's "just the way JS works". Maybe we can think of some clever way to work around it... at some point :)

**Comment by barbieswimcrew** [comment]
Maybe it would already help if you emphasize this particular problem in your documentation. :-)

**Comment by weaverryan** [comment]
Let's try this: https://github.com/symfony/ux/pull/703
