### ISSUE TITLE
[LiveComponent] Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by norkunas** [symfony/ux#729]
So I've found another bug/edge case? when using empty block prefix for the root form.
Reproducer is [here](https://github.com/norkunas/sfux-tests/tree/live-form-dto-edgecase)

Steps:
 - open the page;
 - fill in the title input;
 - observe the error in console.

```
app.80f3d3d8.js:2 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at x (app.80f3d3d8.js:2:18391)
    at app.80f3d3d8.js:2:18840
    at e.value (app.80f3d3d8.js:2:18907)
    at e.value (app.80f3d3d8.js:2:19037)
    at e.value (app.80f3d3d8.js:2:30255)
    at e.value (app.80f3d3d8.js:2:51038)
    at e.value (app.80f3d3d8.js:2:50454)
    at HTMLDivElement.callback (app.80f3d3d8.js:2:47390)
```

**Comment by weaverryan** [comment]
Hmm, that's a good find - thanks again for really trying to break things (for real). Thanks to your reproducer, finding the cause was pretty simple. In `ComponentWithFormTrait`, we have:

```php
#[LiveProp(writable: true, fieldName: 'getFormName()')]
public ?array $formValues = null;
```

I'm not sure what to do here. The problem is that `getFormName()` is ''`, so effectively we have `fieldName: ''`. That... just doesn't really make any sense. 

I think we need to disallow this: throw an exception of `fieldName` is ever set to an empty string. 

To make this work, we would need to take the array of `formValues` and put them on the "top level" data. In your example, if you form had a name, the models would look like `the_form_name.items.0.name`. Without the form name, they would need to become `items.0.name` - so `items` (and any other top-level fields on your form) would become top-level data on the component, as if they were actual fields on your component. I don't think allowing this is possible: on re-render, we would basically need to look for "extra" fields that we don't recognize being sent on the top-level, and set those onto `$formData`. It's... weird.

Is emptying the block prefix a need? Or were you just trying to see what things you could break?

**Comment by norkunas** [comment]
Ok so this mean's that root form without block prefix should not be supported as I asked in my first issue :)

> Is emptying the block prefix a need? Or were you just trying to see what things you could break?

Basically I don't see a need for the root form to be prefixed with name[..] for the input names and that also reduces transporting content size between front and back on re-renders.
If that it is a limitation I will get a long with that. But this doesn't mean that I'm always in control of a form type :)

**Comment by weaverryan** [comment]
> If that it is a limitation I will get a long with that. But this doesn't mean that I'm always in control of a form type :)

The work-around would need to be some sort of mapping conversion - e.g. for the `$formValues` property in `ComponentWithFormTrait`, instead of an empty string for the frontend name, let's pretend we call it `theFormValues` (just as an example). The, via some attribute on the `form` element, we would do a conversion. For example:

```
<form data-model="prefixModelName(theFormValues)|*">
    <input name="firstName">
</form>
```

When the `firstName` field is changed, that gets mapped to a `theFormValues.firstName` model, which is then read (without any server changes) because the frontend name is `theFormValues`.

If we cared enough, we could solve the problem right now with something similar to what I just proposed:

A) Removing `fieldName: 'getFormName()'` so that it uses `formValues` as the frontend name in ALL situations
B) (Assume the form name/block prefix is `post_form`), Changing the default `data-model="*"` that's rendered to `data-model="mapModels(formValues, post_form)|*"`
C) Add some code to the frontend for `mapModels` which would strip the `post_form` prefix from field names and replace it with `formValues`. The `post_form` would be omitted if there is no form name (and then `formValues` is simply used as a prefix).
