### ISSUE TITLE
[LiveComponent] `[name]TargetConnected` does not work when component is re-rendered

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#850]
`[name]TargetConnected` is not called when the component is re-rendered.

Here is my stimulus controller:

```js
import { Controller } from '@hotwired/stimulus';

export default class extends Controller {
    static targets = ['option'];

    declare readonly optionTargets: HTMLLIElement[];

    optionTargetConnected() {
        this.optionTargets.forEach((element) => element.setAttribute('role', 'option'));
    }
}

```
My Live component looks like this: https://github.com/symfony/ux/blob/2.x/ux.symfony.com/templates/components/SearchPackages.html.twig

**Comment by weaverryan** [comment]
Hey @seb-jean!

This is true! Those targets aren't actually removed and re-added, so they are not reinitialized.

But, it's maybe more interesting than that :p. Suppose there are 8 elements showing, then you search, and there are now 4 elements showing. 2 are new, and 2 were there before. In this situation, you will not see ANY targets "reconnect". But shouldn't the 2 new items reconnect?

Behind the scenes, live components (via morphdom) removes elements 5-8, then updates elements 1-4 to match the new 4 elements. Hence, no new elements are added. And so no new targets are connected. If you search again and went from 4 to 8 elements, I believe you *would* see 4 new connected items. Please let me know if you're seeing behavior different than this :).

The solution is to add a `data-live-id` attribute to each element in the list. So, basically on the outer element that's rendered inside the partial - https://github.com/symfony/ux/blob/2.x/ux.symfony.com/templates/components/SearchPackages.html.twig#L12 - so in here - https://github.com/symfony/ux/blob/2.x/ux.symfony.com/templates/main/_package_in_list.html.twig

If this were a real app, I'd use `data-live-id="package-{{ package.id }}"`, but since those packages don't come from the database, you could use anything unique. With this setup, in the previous example, the system SHOULD notice that 6 items were removed, 2 stayed (so no reconnect on those targets) and 2 new ones were added (you should see the connect on these).

Cheers!

**Comment by seb-jean** [comment]
It works !
