### ISSUE TITLE
Proposal: Publish assets also to NPM (as alternative to "virtual packages")

### ISSUE THREAD

**Issue by pableu** [symfony/ux#935]
I understand that UX adds a "virtual package" that links to the code from the composer-package in `vendor/symfony/<package-name>/assets` so we don't have to download it twice (as explained [here](https://symfony.com/doc/current/frontend/ux.html#how-does-symfony-ux-work)).

But this slows our CI-pipeline down because it creates a dependency between the yarn and the composer job. We can't do `yarn install` without the vendor-directory from `composer install`. So we cannot run the two jobs in parallel any longer.

How about _also_ publishing the JavaScript code to NPM? Then we could just add real packages to our `package.json` and the `yarn install` would be fine without the vendor-directory.

**Comment by weaverryan** [comment]
Hi!

I'm ok with this in theory, though it could cause some complications in practice with versioning. Right now, the virtual package system means that you will always have a PHP package that's compatible with the JS code, as they're shipped together. If we ship them as separate packages, there's no way to enforce this - e.g. you could stay on version 2.9 of the JS assets, even if you bump your PHP dependencies that work with those to some new 3.0 version. I don't love that - but I can't think of a way to tie these together in a way where you would at least be notified of an incompatibility.

**Comment by jmariller** [comment]
Hi @weaverryan thank you so much for getting back to us so quickly, and I agree with your comment. Just an idea/question, do you think it would be possible to have Webpack Encore trigger a warning (or even better, break) when running the compilation if there is a difference between the vendor and npm versions?

**Comment by weaverryan** [comment]
I'm not sure... but maybe (?) via `stimulus-bridge`... though I think we would need to... potentially parse `composer.lock` from Node to see the exact version of libraries. Seems a bit weird, but quite possibly straightforward.

I'll see if I can check into this (npm packages) next week - we just need the publishing of packages to be as automated as the PHP publishing.

**Comment by pableu** [comment]
Thanks for your thoughts @weaverryan and @jmariller. I think that would be a great solution for our use case.

**Comment by weaverryan** [comment]
FYI - I haven't forgotten about this - but summer vacations are hitting :)

**Comment by YummYume** [comment]
Hello :) Is this still being considered?

For my part, we currently have quite a lot of problems with the Symfony UX packages using local files from the vendor, most notably because it seems not to be very well supported by some package managers : 

- Yarn 3.6 creates different checksums for these packages after almost every install, despite using Docker, which forces us to disable some security features in our CI for it to pass. It also creates unnecessary changes to the lock file in PRs
- Bun (which is being considered to speed up install/build time in projects and in the CI) doesn't seem to support the `file:` syntax, or at least it needs some workaround (it may be lacking permissions to those files)

It also comes with the fact that we always have to install the composer packages first, as stated above.

It would really help to have the packages available on NPM, and worst case scenario, it would be our responsibility to make sure the version matches the one installed in our composer.json. Doesn't seem that bad to me.

**Comment by weaverryan** [comment]
Yup - I’m thinking this might be handier also for AssetMapper - I’m going to think about it in the next few weeks. It’s a matter of getting the release process correct across the sub-tree split and multiple repos.

**Comment by weaverryan** [comment]
Hi!

After looking into this, we're going to decline publishing real packages. This will be disappointing to some people - and I'm sorry about that. We (Symfony) are moving towards the no-build AssetMapper approach. In that case, there is no disadvantage to having the JS code inside the PHP package. In fact, it makes life easier (my previous comment about AssetMapper possibly taking advantage of standalone packages turned out not to be true). And so, I don't want to introduce multiple ways (pure npm package or local js files in `vendor/`) to point to packages nor add overhead of publishing npm packages.

Again, sorry for those who wanted this! OSS is always a balance - thanks for the conversation.
